CompanyInformationTracker/Models/Referrer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CompanyInformationTracker.Models
{
    [Table("tbl_REFERRER")]
    public class Referrer
    {
        [Required]
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("REFERRER_ID")]
        public long Id { get; set; }

        [Required]
        [Display(Name = "Referrer Name")]
        [MaxLength(50)]
        [Column("SOURCE_NAME", TypeName = "varchar")]
        [Index(IsUnique = true)]
        public string SourceName { get; set; }
    }
}

CompanyInformationTracker/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompanyInformationTracker.Models;

namespace CompanyInformationTracker.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        //The following actions for CRUDing internal member types
        public PartialViewResult MemberType()
        {
            return PartialView("InternalType/List");
        }

        public ActionResult GetInternalTypes()
        {
            using(ApplicationDbContext db = new ApplicationDbContext())
            {
                var types = db.InternalMemberTypes.OrderBy(a => a.Id).ToList();
                return Json(new { data = types }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult CreateInternalType()
        {
            return PartialView("InternalType/Create");
        }

        [HttpPost]
        public ActionResult CreateInternalType(InternalMemberType type)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    db.InternalMemberTypes.Add(type);
                    db.SaveChanges();
                    status = true;
                }
            }

            return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        public ActionResult EditInternalType(long id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var type = db.InternalMemberTypes.Where(row => row.Id == id).FirstOrDefault();
                return PartialView("InternalType/Edit", type);
            }
        }

        [HttpPost]
        public ActionResult EditInternalType(InternalMemberType type)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    db.InternalMemberTypes.Attach(type);
                    var entry = db.Entry(type);
                    entry.Property(e => e.TypeName).IsModified = true;

                    db.SaveChanges();
                    status = true;
                }
            }

            return new JsonResult { Data = new { status = status } };
        }

        public ActionResult DeleteInternalType(long id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var type = db.InternalMemberTypes.Where(row => row.Id == id).FirstOrDefault();
                return PartialView("InternalType/Delete", type);
            }
        }

        [HttpPost, ActionName("DeleteInternalType")]
        public ActionResult _DeleteInternalType(long id)
        {
            bool status = false;
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var v = db.InternalMemberTypes.Where(a => a.Id == id).FirstOrDefault();
                if (v != null)
                {
                    db.InternalMemberTypes.Remove(v);
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        //The following actions for CRUDing legal entity types
        public PartialViewResult LegalType()
        {
            return PartialView("LegalType/List");
        }

        public ActionResult GetLegalTypes()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var types = db.LegalEntityTypes.OrderBy(a => a.Id).ToList();
                return Json(new { data = types }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult CreateLegalType()
        {
            return PartialView("LegalType/Create");
        }

        [HttpPost]
        public ActionResult CreateLegalType(LegalEntityType type)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    db.LegalEntityTypes.Add(type);
                    db.SaveChanges();
                    status = true;
                }
            }

            return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        public ActionResult EditLegalType(long id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var type = db.LegalEntityTypes.Where(row => row.Id == id).FirstOrDefault();
                return PartialView("LegalType/Edit", type);
            }
        }

        [HttpPost]
        public ActionResult EditLegalType(LegalEntityType type)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    db.LegalEntityTypes.Attach(type);
                    var entry = db.Entry(type);
                    entry.Property(e => e.TypeName).IsModified = true;

                    db.SaveChanges();
                    status = true;
                }
            }

            return new JsonResult { Data = new { status = status } };
        }

        public ActionResult DeleteLegalType(long id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var type = db.LegalEntityTypes.Where(row => row.Id == id).FirstOrDefault();
                return PartialView("LegalType/Delete", type);
            }
        }

        [HttpPost, ActionName("DeleteLegalType")]
        public ActionResult _DeleteLegalType(long id)
        {
            bool status = false;
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var v = db.LegalEntityTypes.Where(a => a.Id == id).FirstOrDefault();
                if (v != null)
                {
                    db.LegalEntityTypes.Remove(v);
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        //The following actions for CRUDing member demography information
        public PartialViewResult Demography()
        {
            return PartialView("Demography/List");
        }

        public ActionResult GetDemographies()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var types = db.MemberDemographies.OrderBy(a => a.Id).ToList();
                return Json(new { data = types }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult CreateDemography()
        {
            return PartialView("Demography/Create");
        }

        [HttpPost]
        public ActionResult CreateDemography(MemberDemography type)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    db.MemberDemographies.Add(type);
                    db.SaveChanges();
                    status = true;
                }
            }

            return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        public ActionResult EditDemography(long id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var type = db.MemberDemographies.Where(row => row.Id == id).FirstOrDefault();
                return PartialView("Demography/Edit", type);
            }
        }

        [HttpPost]
        public ActionResult EditDemography(MemberDemography type)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    db.MemberDemographies.Attach(type);
                    var entry = db.Entry(type);
                    entry.Property(e => e.DemographyName).IsModified = true;

                    db.SaveChanges();
                    status = true;
                }
            }

            return new JsonResult { Data = new { status = status } };
        }

        public ActionResult DeleteDemography(long id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var type = db.MemberDemographies.Where(row => row.Id == id).FirstOrDefault();
                return PartialView("Demography/Delete", type);
            }
        }

        [HttpPost, ActionName("DeleteDemography")]
        public ActionResult _DeleteDemography(long id)
        {
            bool status = false;
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var v = db.MemberDemographies.Where(a => a.Id == id).FirstOrDefault();
                if (v != null)
                {
                    db.MemberDemographies.Remove(v);
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        //The following actions for CRUDing referrer
        public PartialViewResult Referrer()
        {
            return PartialView("Referrer/List");
        }

        public ActionResult GetReferrers()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var types = db.Referrers.OrderBy(a => a.Id).ToList();

CompanyInformationTracker/Views/Settings/Referrer/Create.cshtml
@model CompanyInformationTracker.Models.Referrer

@{
    ViewBag.Title = "Referrer";
}

@using (Html.BeginForm("CreateReferrer", "Settings", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add New Referrer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SourceName, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.SourceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SourceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CompanyInformationTracker/Views/Settings/Referrer/Delete.cshtml
@model CompanyInformationTracker.Models.Referrer

@{
    ViewBag.Title = "Delete Referrer";
}

<h2>Delete!</h2>

<h4>Are you sure you want to delete this?</h4>
@using (Html.BeginForm("DeleteReferrer", "Settings", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.Id)
    <div class="form-group">
        <label>Referrer Name: </label> @Model.SourceName
    </div>

    <div>
        <input type="submit" value="Delete" />
    </div>
}

CompanyInformationTracker/Views/Settings/Referrer/Edit.cshtml
@model CompanyInformationTracker.Models.Referrer

@{
    ViewBag.Title = "Edit Referrer";
}

@using (Html.BeginForm("EditReferrer", "Settings", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Referrer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SourceName, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.SourceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SourceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CompanyInformationTracker/Views/Settings/Referrer/List.cshtml
@{
    ViewBag.Title = "Referrer List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="tablecontainer">

    <div style="height:auto;">
        <h3 style="float:left;">All the referrers</h3>
        <a class="popup btn btn-primary company-add-btn" href="CreateReferrer">Create New Type</a>
    </div>
    <hr style="clear:both;" />
    
    <div>
        <table id="referrerDatatable" style="width: 100%;">
            <thead>
                <tr>
                    <th>Source Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
        </table>
    </div>

    <style type="text/css">
        #referrerDatatable {
            margin: 0;
            border: 0;
            text-align: left;
        }

        table.dataTable thead th, table.dataTable thead td {
            padding: 5px 10px;
            border-bottom: 1px solid #C0C0C0;
        }

        table.dataTable tbody th, table.dataTable tbody td {
            padding: 5px 10px;
            border-bottom: 1px solid #C0C0C0;
        }
    </style>

    <script>
        $(document).ready(function () {
            var oTable = $('#referrerDatatable').DataTable({
                "ajax": {
                    "url": '/Settings/GetReferrers',
                    "type" : "get",
                    "datatype" : "json"
                },
                "paging": true,
                "ordering": false,
                "info": false,
                "searching": true,
                "columns": [
                    { "data": "SourceName", "width": "auto" },
                    {
                        "data": "Id", "width": "auto", "render": function (data) {
                            return '<a class="popup" href="/Settings/EditReferrer/' + data + '">Edit</a>';
                        }
                    },
                    {
                        "data": "Id", "width": "auto", "render": function (data) {
                            return '<a class="popup" href="/Settings/DeleteReferrer/' + data + '">Delete</a>';
                        }
                    }
                ]
            })

            $('.tablecontainer').on('click', 'a.popup', function (e) {
                e.preventDefault();
                OpenPopup($(this).attr('href'));
            })
            function OpenPopup(pageUrl) {
                var $pageContent = $('<div/>');
                $pageContent.load(pageUrl, function () {
                    $('#popupForm', $pageContent).removeData('validator');
                    $('#popupForm', $pageContent).removeData('unobtrusiveValidation');
                    $.validator.unobtrusive.parse('form');

                });

                $dialog = $('<div class="popupWindow box-shadow-popup shadow-popup" style="overflow:hidden;font-size:large;font-family:\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;"></div>')
                          .html($pageContent)
                          .dialog({
                              draggable: false,
                              autoOpen: false,
                              resizable: false,
                              model: true,
                              closeOnEscape: true,
                              //title: 'Popup Dialog',
                              height: 270,
                              width: 450,
                              close: function () {
                                  $dialog.dialog('destroy').remove();
                              }
                          })
                

                $('.popupWindow').on('submit', '#popupForm', function (e) {
                    var url = $('#popupForm')[0].action;
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: $('#popupForm').serialize(),
                        success: function (data) {
                            if (data.status) {
                                $dialog.dialog('close');
                                oTable.ajax.reload();
                            }
                        }
                    })

                    e.preventDefault();
                })

                $dialog.dialog('open');
            }
        })
    </script>
</div>